name: Mirror Repository

on:
  workflow_dispatch:
    inputs:
      git_url:
        description: 'Git URL of the repository to mirror'
        required: true
        default: 'https://github.com/numpy/numpy.git'

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Clone the source repository
      run: |
        git clone --mirror ${{ github.event.inputs.git_url }} source-repo
