name: Example Workflow Docker
on: workflow_dispatch
jobs:
  security:
    runs-on: ubuntu-latest
    container: docker://synopsys/blackduck-docker-inspector:latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 11
      uses: actions/setup-java@v4 
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run Synopsys Detect
      uses:  docker://synopsys/blackduck-docker-inspector:latest
      with:
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          OUTPUT_FILE: output.json
         
      env:
        NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
